#!/usr/bin/env bash
# .jst/bootstrap.sh — per-worktree bootstrap hook for markdown-editor
# Runs automatically via jira-task-executor step 1 when someone works in this worktree.
# Idempotent: safe to re-run. Non-zero exit is reported but doesn't block the executor.

set -euo pipefail

# ---------------------------------------------------------------------------
# Environment contract — exported by the executor (JST_*). Defaults allow
# running this script by hand for debugging.
# ---------------------------------------------------------------------------
ISSUE_KEY="${JST_ISSUE_KEY:-$(git branch --show-current | sed -E 's#^[^/]+/([A-Z][A-Z0-9]+-[0-9]+).*#\1#')}"
WORKTREE_DIR="${JST_WORKTREE_DIR:-$(git rev-parse --show-toplevel)}"
BRANCH="${JST_BRANCH:-$(git branch --show-current)}"
PARENT_BRANCH="${JST_PARENT_BRANCH:-}"
PROJECT_KEY="${JST_PROJECT_KEY:-PROJ}"

cd "$WORKTREE_DIR"

# ---------------------------------------------------------------------------
# Instance index — deterministic from issue number so the same worktree
# always gets the same port across re-runs. Base port 5174 for first copy.
# ---------------------------------------------------------------------------
ISSUE_NUM="${ISSUE_KEY##*-}"
INSTANCE=$(( (ISSUE_NUM % 100) + 1 ))
DEV_PORT=$(( 5174 + INSTANCE ))

echo "bootstrap: $ISSUE_KEY on $BRANCH (parent: ${PARENT_BRANCH:-none})"
echo "bootstrap: instance $INSTANCE — dev server on :$DEV_PORT"

# ---------------------------------------------------------------------------
# 1. Install npm dependencies (each worktree has its own node_modules).
#    Skip when already satisfied.
# ---------------------------------------------------------------------------
if [ ! -d "$WORKTREE_DIR/node_modules" ] || [ ! -f "$WORKTREE_DIR/node_modules/.package-lock.json" ]; then
  echo "bootstrap: installing npm packages..."
  npm install --silent
  # Touch a marker so we can detect if package-lock.json changed
  cp package-lock.json node_modules/.package-lock.json 2>/dev/null || true
else
  echo "bootstrap: npm packages already installed"
fi

# ---------------------------------------------------------------------------
# 2. Write per-worktree .env.local with the unique dev port.
#    Vite reads PORT from env; we also export it for npm run dev.
# ---------------------------------------------------------------------------
cat > "$WORKTREE_DIR/.env.local" <<ENV
# Generated by .jst/bootstrap.sh for $ISSUE_KEY — do not edit by hand.
PORT=$DEV_PORT
VITE_PORT=$DEV_PORT
ENV

echo "bootstrap: wrote .env.local with PORT=$DEV_PORT"
echo "bootstrap: ready — start the dev server with 'npm run dev' (serves on :$DEV_PORT)"